baseurl = "https://raghuvanshy.com/"
canonifyurls = true
disqusShortname = "yourdiscussshortname"
languagecode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "coder"
title = "Raghuvanshy"
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2
[params]
author = "Gaurav Raghuvanshy aka codeRiot"
custom_css = []
description = "codeRiot's personal website"
hidecopyright = false
hidecredits = false
info = "Full Stack Golang Dev and CLI wizard level 3"
keywords = "blog,developer,personal,golang,vi,linux"
[[params.social]]
name = "Github"
url = "https://github.com/raghuvanshy/"
weight = 1
[[params.social]]
name = "Twitter"
url = "https://twitter.com/johndoe/"
weight = 2
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/coderiot/"
weight = 3
